name: figma_theme
description: Annotations for the figma_theme_generator.
version: 0.1.1
homepage: https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  meta: ^1.1.8
  collection: ^1.14.13
  flutter:
    sdk: flutter
