name: figma_to_flutter_cli
description: A cli for converting Figma files to Flutter widgets.
authors:
- Alo√Øs Deniel <alois.deniel@outlook.com>
environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

dependencies:
  args: 1.4.4
  figma_to_flutter:
 
dependency_overrides:
  figma_to_flutter:
    path: ../src